Fix: Caused by: java.lang.NoSuchMethodError: 'void com.palmergames.bukkit.towny.command.TownCommand.townSetSpawn(org.bukkit.entity.Player, com.palmergames.bukkit.towny.object.Town, boolean)' Optimize imports Update dependencies Version 0.0.9-SNAPSHOT